# Generated by Django 4.2.13 on 2024-06-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSyncRevisions",
            fields=[
                (
                    "datastore_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("datastore_name", models.CharField(max_length=100, unique=True)),
                ("sequence_id", models.IntegerField()),
            ],
            options={
                "db_table": "data_sync_revisions",
            },
        ),
    ]
