# Generated by Django 3.2.10 on 2021-12-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncRevisions',
            fields=[
                ('datastore_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('datastore_name', models.CharField(max_length=100, unique=True)),
                ('sequence_id', models.IntegerField()),
            ],
            options={
                'db_table': 'data_sync_revisions',
            },
        ),
    ]
