# See http://pre-commit.com/#python
# See https://github.com/pre-commit/pre-commit-hooks
# Run 'pre-commit install' to install the pre-commit hooks
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: detect-private-key
  # ruff handles quoting
  # - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
    exclude: (.csv|.tsv)$
  - id: pretty-format-json
    args: ['--no-sort-keys', '--autofix']
  # don't commit directly to main or master
  - id: no-commit-to-branch

- repo: https://github.com/adamchainz/django-upgrade
  rev: 1.22.2
  hooks:
    - id: django-upgrade
      args: [--target-version, "4.2"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.3
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
    - id: yamllint
      args: ['-c.yamllint-config.yml', '-s']

## ruff does not re-implement all of pylint,
## see https://github.com/astral-sh/ruff/issues/970
- repo: https://github.com/PyCQA/pylint
  rev: v3.3.3
  hooks:
    - id: pylint
      args:
        # black is controlling line length:
        - --disable=line-too-long
        # let's not worry too much right now about dup code.
        - --disable=duplicate-code
        # Decided to use _id and _rev variables to indicate
        # variables controlled by reldatasync, so this would
        # complain about protected access all throughout this code
        - --disable=protected-access
        - --disable=fixme
        - --disable=import-error
        - --disable=logging-fstring-interpolation
        - --disable=missing-class-docstring
        - --disable=missing-function-docstring
        - --disable=missing-module-docstring
        - --disable=too-few-public-methods
        - --disable=too-many-arguments
        # - --disable=too-many-branches
        - --disable=too-many-locals
        # isort is taking care of import order:
        - --disable=wrong-import-order
        # re-enable these args
        - --disable=unused-argument
        - --disable=invalid-name
        - --disable=raise-missing-from

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: forbid-crlf
    exclude: (gradlew.bat)
  # don't just remove, seems dangerous
  # - id: remove-crlf
  - id: forbid-tabs
    exclude: (README.md|.tsv)
  # don't just remove, seems dangerous
  # - id: remove-tabs
