# Generated by Django 4.2.13 on 2024-06-22 20:07

import django.db.models.deletion
import django.utils.timezone
import reldatasync.util
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "_id",
                    models.CharField(
                        default=reldatasync.util.uuid4_string,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "_rev",
                    models.CharField(
                        help_text="A vector clock representing a revision.",
                        max_length=2000,
                    ),
                ),
                ("_seq", models.IntegerField(help_text="Sequence number.")),
                (
                    "_deleted",
                    models.BooleanField(
                        blank=True,
                        help_text="True if the document is deleted.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "_id",
                    models.CharField(
                        default=reldatasync.util.uuid4_string,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "_rev",
                    models.CharField(
                        help_text="A vector clock representing a revision.",
                        max_length=2000,
                    ),
                ),
                ("_seq", models.IntegerField(help_text="Sequence number.")),
                (
                    "_deleted",
                    models.BooleanField(
                        blank=True,
                        help_text="True if the document is deleted.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("residence", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("birth_date", models.DateField()),
                ("created_dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("email", models.EmailField(max_length=254)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="test_reldatasync_app.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
